### ISSUE TITLE
Both the description column and the value column should have a Tooltip

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#11]
Is there any way to set the tooltip of value column. It could be also bonded to Description.

**Comment by smourier** [comment]
The grid name colomn uses the optional `DescriptionAttribute `for its tooltip. By default there's none.

        [Category("Dates and Times")]
        [Description("This is a timespan")]
        public TimeSpan TimeSpan
        {
            get { return GetProperty<TimeSpan>(); }
            set { SetProperty(value); }
        }
        
This will render like this:
![propertygrid_value_tooltip](https://user-images.githubusercontent.com/5328574/29807043-6bc4f27a-8c92-11e7-9604-6d2420cb7ada.png)

![propertygrid_description_tooltip](https://user-images.githubusercontent.com/5328574/29807030-5ac123f4-8c92-11e7-97e0-9138abaf965c.png)

If you want to change that behavior here is the corresponding xaml in PropertyGrid.xaml:

            <DataGridTextColumn Header="Name" Binding="{Binding DisplayName}" Width="SizeToCells" IsReadOnly="True" Foreground="Black">
                <DataGridTextColumn.CellStyle>
                    <Style TargetType="DataGridCell">
                        
                        <Setter Property="ToolTip" Value="{Binding Description}" />
                    </Style>
                </DataGridTextColumn.CellStyle>
            </DataGridTextColumn>
            
For the grid value column, the default behavior is to use the cell tooltip for validation errors.
You could add another tooltip for the whole column, but the design decision was it's quite dependent on the editor.
So you can as always use a custom editor to add a specific tooltip, for example the sample app.xaml can be modified like this (tooltip is bound to TextValue but it could be bound to any path from the PropertyGridProperty class which is the DataContext)

 
    <DataTemplate x:Key="PercentEditor">
        <Slider ToolTip="{Binding TextValue}" Orientation="Horizontal" IsSnapToTickEnabled="True"
           Value="{Binding Value, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, Converter={StaticResource ChangeTypeConverter}, ConverterParameter={x:Type sys:Double}}"
            Minimum="0"
            Maximum="100"
            Interval="1"
            IsEnabled="{Binding IsReadWrite}"
            Background="{Binding IsDefaultValue, Converter={StaticResource BoolToDefaultValueBackgroundConverter}}"></Slider>
    </DataTemplate>

The will render like this:

![propertygrid_value_tooltip](https://user-images.githubusercontent.com/5328574/29807053-70675548-8c92-11e7-8b86-5514f22481a4.png)

**Comment by ShannonZ** [comment]
Thank you very much. This solved my problem.
