### ISSUE TITLE
How to customize the tooltip when exception thrown?

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#12]
# Is it possible to customize the tooltip to display DataValidationError (without modifying the source code of SF )?
   Alternatively, is there any way to recover the value to old value if data validation fails (when lost focus)?
### Expected outcome
![untitled](https://user-images.githubusercontent.com/7865691/29951372-e1face88-8ef4-11e7-9719-d7fbdfbe082e.gif)

### Environment

- SoftFluent.Windows __v1.0.0__
- Windows OS __win7 x64__
- Visual Studio __2017__
- .NET Framework __4.5__

**Comment by smourier** [comment]
First thing to understand is property values are not committed (not set on the bound model property) while there are errors.
So even if you see a wrong value in an editor, that doesn't mean the property contains this value, only the editor (for example a TextBox) contains the wrong value.

About changing the tooltip in a global way without changing the PropertyGrid's source, the validation error red box is by default enabled on the final datatemplate that is defined in the list of PropertyGridDataTemplates in propertygrid.xaml. This final datatemplate is "fallback" data template for properties that don't match anything else. The source in PropertyGrid.xaml is this:

    ...
    <windows:PropertyGridDataTemplate>
        <DataTemplate>
            <TextBox Text="{Binding TextValue, UpdateSourceTrigger=PropertyChanged, ValidatesOnDataErrors=True}" Style="{StaticResource ValidationTextBox2}" />
        </DataTemplate>
    </windows:PropertyGridDataTemplate>
    ...
    <Style x:Key="ValidationTextBox2" TargetType="{x:Type TextBox}">
        <Setter Property="DataGridCell.ToolTip" Value="{Binding RelativeSource={RelativeSource Self}, Path=(Validation.Errors).CurrentItem.ErrorContent}"/>
    </Style>
    ....


If you want to change that, you'll need to code something like this in your main window code:

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            
            var tc = (DataGridTemplateColumn)MyGrid.BaseGrid.Columns[1]; // get values columns
            var selector = (PropertyGridDataTemplateSelector)tc.CellTemplateSelector; // get pg data template selector
            var fallback = selector.DataTemplates.Last(); // get last (fallback)
            selector.DataTemplates.Remove(fallback); // remove it
            var newFallback = (PropertyGridDataTemplate)FindResource("FallbackSelector"); // get a custom one defined in App.xaml for example
            selector.DataTemplates.Add(newFallback); // add it to the end so it becomes the fallback selector
        }
    }

I suppose you declare a "FallbackSelector" resource in your App.xaml, like this (sfw is the property grid's namespace):

        <sfw:PropertyGridDataTemplate x:Key="FallbackSelector">
            <DataTemplate>
                <TextBox Style="{StaticResource NoValidationTextBox}" Text="{Binding TextValue, UpdateSourceTrigger=PropertyChanged}" />
            </DataTemplate>
        </sfw:PropertyGridDataTemplate>

As you see, I've removed the ValidatesOnDataErrors and changed the style to target a new custom one, which I've defined like this for example:

        <Style x:Key="NoValidationTextBox" TargetType="{x:Type TextBox}">
            <Setter Property="Validation.ErrorTemplate">
                <Setter.Value>
                    <ControlTemplate>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
            <Style.Triggers>
                <Trigger Property="Validation.HasError" Value="true">
                    <Setter Property="DataGridCell.ToolTip">
                        <Setter.Value>
                            <WrapPanel Width="100" Height="100" Background="Yellow">
                                <TextBlock TextWrapping="WrapWithOverflow">Some error happened</TextBlock>
                            </WrapPanel>
                        </Setter.Value>
                    </Setter>
                </Trigger>
            </Style.Triggers>
        </Style>
        
You can change the ControlTemplate (I've put nothing here), and/or the DataGridCell.Tooltip
This is how this custom fallback data template looks:

![propertygrid_fallback_selector](https://user-images.githubusercontent.com/5328574/29961363-b8b5ca0e-8eff-11e7-9daf-c3b46c0f8740.png)

**Comment by ShannonZ** [comment]
Thank you very much!
