### ISSUE TITLE
Customized editor cannot update data

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#13]
Source Code [can be download here](https://github.com/ShannonZ/playground.git)
![capture-3](https://user-images.githubusercontent.com/7865691/30009287-cbbb9f78-9159-11e7-8c6b-c506b1f41da0.gif)

**Comment by meziantou** [comment]
To correctly update the value, you have to set the `UpdateSourceTrigger` property of the binding to `PropertyChanged` or `LostFocus`.

    <DataTemplate x:Key="MyEditor">
        <Controls:NumericUpDown Minimum="0"  Maximum="10000"  Interval="1" StringFormat="00.000 munit"
            Value="{Binding Value, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
    </DataTemplate>

**Comment by ShannonZ** [comment]
@meziantou  You can change MyEditor as you comment. The problem still exists. After changing any content, it will restore to the old value immediately.

**Comment by smourier** [comment]
Difficult to say w/o a piece of reproducing code.

**Comment by ShannonZ** [comment]
@smourier  It is strange... When using direct binding  the value of NumericUpDown with Model.SF, all is ok. But when using NumericUpDown in Custom Editor, the value cannot update, the setter of SF is not even triggered.

**Comment by ShannonZ** [comment]
I found that this issue was caused by MahApp.
