### ISSUE TITLE
Width parse error

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#14]
Source code for this issue [github](https://github.com/ShannonZ/playground.git)

- Reproduce
![capture-8](https://user-images.githubusercontent.com/7865691/30194814-097af5c6-9488-11e7-8ce8-f2862a0ad759.gif)

- Expected Results
The width of editor in different tab items should be corrected!

**Comment by ShannonZ** [comment]
@smourier  
` <TabItem  Header="SF1" >
                    <windows:PropertyGrid x:Name="pg1"/>
   </TabItem>
   <TabItem Header="SF2" >
                    <windows:PropertyGrid x:Name="pg2"  />
    </TabItem>`

`m = new Model();
pg1.SelectedObject = m;
 pg2.SelectedObject = m;`

**Comment by smourier** [comment]
If you start a project from scratch and add a standard WPF TabControl, like this:

        <TabControl>
            <TabItem  Header="SF1" >
                <windows:PropertyGrid x:Name="pg1" Grid.Column="0"  ScrollViewer.VerticalScrollBarVisibility="Auto" ScrollViewer.HorizontalScrollBarVisibility="Hidden" />
            </TabItem>
            <TabItem Header="SF2" >
                <windows:PropertyGrid x:Name="pg2" Grid.Column="0"  ScrollViewer.VerticalScrollBarVisibility="Auto" ScrollViewer.HorizontalScrollBarVisibility="Hidden" />
            </TabItem>
        </TabControl>

it works fine. So I guess it's related to Mahapps, maybe due to the funny animation transition when you change tabs.

**Comment by ShannonZ** [comment]
@smourier  I think this is a problem of SoftFluent.Windows. If I put a NumericUpDown in a Tab directly all is fine.

**Comment by ShannonZ** [comment]
@smourier  How SF decide the width of editor？

**Comment by smourier** [comment]
I clearly don't agree on that. Remove Mahapps, and everything work as expected.

**Comment by ShannonZ** [comment]
I agree with you.

**Comment by ShannonZ** [comment]
It was produced by the MahApp preset Expander style.
