### ISSUE TITLE
How to call an customized  Validation function

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#17]
**For problem reproduction: https://github.com/ShannonZ/playground**   

**I implemented my version of  IDataErrorInfo like this:**
![1](https://user-images.githubusercontent.com/7865691/34552864-1bb1482e-f15f-11e7-800a-ba44c702dc9c.jpg)

![2](https://user-images.githubusercontent.com/7865691/34552853-103d8e3a-f15f-11e7-83cf-5d2466ca9cd6.jpg)
But it seems that the validation cannot be triggered when using as a SelectedObject.
![3](https://user-images.githubusercontent.com/7865691/34552869-22f5fcf6-f15f-11e7-815a-e26f39d04a1c.jpg)

What shoud I do to make my own validation procedure work?

**Comment by smourier** [comment]
Make sure you also test for columnName == null (called by the system to validate all columns).

**Comment by ShannonZ** [comment]
@smourier  After making changes in the custom editor, I traced into the code. I found that the program did not goto the **public string this[string ColumnName]** part.

**Comment by smourier** [comment]
In fact, AutoObject already implements IDataErrorInfo, so you just need to override `protected virtual void Validate(IList<string> errors, string memberName)` and add error(s) to the `errors` parameters if there's an error.

**Comment by ShannonZ** [comment]
The direct binding example used the same class deviated from AutoObject. Why it works?

**Comment by smourier** [comment]
If you change the TEEditor and set UpdateSourceTrigger=PropertyChanged (which is how it should be) instead of LostFocus, it's called everytime (otherwise it's only called when you change between pressing + and -). That's all I can say, the reproducing app is not minimal enough to trace what's going on.

**Comment by ShannonZ** [comment]
@smourier  I've tried all your suggestions but the problem was still not solved.
I re-upload a minimal project https://github.com/ShannonZ/playground

**Comment by smourier** [comment]
Ok, now I reproduce, in fact the original sample behaves the same. This is currently by design. I'll see how we could implement this...

**Comment by ShannonZ** [comment]
The problem was not caused by AutoObject. I changed the code from class MainViewModel:AutoObject, IDataErrorInfo to **class MainViewModel: IDataErrorInfo**,  problem still existed.
Can you give some advise so that I cant  use some customized validation rules? I have to finish it as soon as possible. Any ideas will be appreciated!

**Comment by smourier** [comment]
You need to change the behavior of the `PropertyGridProperty` class so that it replicates the errors of the property it's connected to. To do that, you can write your own version of the PropertyGridProperty class or you can use the IActivator interface feature of the property grid like I demonstrate here.

You need to put that code somewhere it runs very early, for example in the Startup code:

    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            // register my custom activator
            ServiceProvider.Current.SetService(typeof(IActivator), new CustomActivator());
        }

        // my custom activator
        private class CustomActivator : BaseActivator
        {
            public override object CreateInstance(Type type, params object[] args)
            {
                if (type == typeof(PropertyGridProperty))
                    return new CustomProperty((PropertyGridDataProvider)args[0]);

                return base.CreateInstance(type, args);
            }
        }

        // my custom PropertyGrid property
        private class CustomProperty : PropertyGridProperty
        {
            public CustomProperty(PropertyGridDataProvider dataProvider) : base(dataProvider)
            {
            }

            protected override void Validate(IList<string> errors, string memberName)
            {
                // check the connected object supports IDataErrorInfo 
                if (DataProvider.Data is IDataErrorInfo ao)
                {
                    // use the name of this instance as the member name
                    var error = ao[Name];
                    if (error != null)
                    {
                        errors.Add(error);
                    }
                }
                base.Validate(errors, memberName);
            }
        }
    }

**Comment by ShannonZ** [comment]
I've tried the later solution you advised but it didn't work’ as expected. 
Is it possible to delete or block the Validation in PropertyGridProperty class?If yes, how ?

**Comment by smourier** [comment]
Don't know what you did, but the solution works fine with the original PropertyGrid sources and with your playground as well.

**Comment by ShannonZ** [comment]
Thanks a lot! I will try the solution tomorrow~ my server is updating now

**Comment by ShannonZ** [comment]
Your solution works well enough. Thank you very much!

**Comment by ShannonZ** [comment]
@smourier  I found a critical side effect for this solution: all Set/GetProperty cannot work in current environment, All bindings are failed to update.

**Comment by my151and** [comment]
I met the same problem. How to solve it? I used INotifyDataErrorInfo but it didn't show any error information.

**Comment by my151and** [comment]
How to block the Validations implemented by AutoObject or PropertyGrid?
I think the library should only generate corresponding Controls. Data Validation\Exception catching should do by who use this library.
@ShannonZ  @smourier
