### ISSUE TITLE
How to block the Validations implemented by AutoObject or PropertyGrid?

### ISSUE THREAD

**Issue by my151and** [SoftFluent/SoftFluent.Windows#18]
I create a class implementing INotifyDataErrorInfo and bound to sf. 
But when  ErrorChanges(HasError= true), no error information will show in UI.
ValidatesOnNotifyDataErrors was set to True in the corresponding Editor.

I want to know how to block the  validation behaviors implemented by AutoObject or PropertyGrid?
I just want to use SF only to auto generate UI controls, no anything more.

**Comment by smourier** [comment]
Validation in the grid is a standard WPF validation. AutoObject is just a utility class, it's not necessary to use the PropertyGrid. Maybe your implementation has issues. You might want to check my answer here: https://stackoverflow.com/questions/34665650/force-inotifydataerrorinfo-validation about that subject.

Here is a sample POCO class with a Text property that works fine:

    public class MyObject : INotifyDataErrorInfo, IDataErrorInfo, INotifyPropertyChanged
    {
        public event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;
        public event PropertyChangedEventHandler PropertyChanged;

        public IEnumerable GetErrors(string propertyName)
        {
            if (propertyName == null || propertyName == nameof(Text))
            {
                if (string.IsNullOrWhiteSpace(_text))
                    yield return "Text must not be empty.";
            }
        }

        public bool HasErrors => (GetErrors(null)?.Cast<object>()?.Any()).GetValueOrDefault();

        private string _text;
        public string Text
        {
            get => _text;
            set
            {
                if (_text == value)
                    return;

                _text = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Text)));
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(HasErrors)));
                if ((GetErrors(nameof(Text))?.Cast<object>()?.Any()).GetValueOrDefault())
                {
                    ErrorsChanged?.Invoke(this, new DataErrorsChangedEventArgs(nameof(Text)));
                }
            }
        }

        string IDataErrorInfo.Error => ((IDataErrorInfo)this)[null];
        string IDataErrorInfo.this[string columnName] => GetErrors(columnName)?.Cast<object>()?.FirstOrDefault()?.ToString();
    }

with a XAML like this:

    <Grid>
        <Grid.Resources>
            <samples:MyObject x:Key="Customer"/>
        </Grid.Resources>
        <sfw:PropertyGrid Name="MyGrid" xmlns:sfw="clr-namespace:SoftFluent.Windows;assembly=SoftFluent.Windows" SelectedObject="{StaticResource Customer}" />
    </Grid>


![propgrid](https://user-images.githubusercontent.com/5328574/36932725-cfa5f5d2-1ecd-11e8-890f-e53ca7dee91d.png)

**Comment by my151and** [comment]
https://github.com/my151and/sfValidation.git
I copy your code but it still shows none validation error info.

**Comment by smourier** [comment]
Yes, you need to modify your App' startup like described in issue here: https://github.com/SoftFluent/SoftFluent.Windows/issues/17

**Comment by my151and** [comment]
The same problem remained after adding those startup code like #17 
https://github.com/my151and/Reproduce.git

**Comment by smourier** [comment]
Well, this is a problem with your implementation. Read my post on stackoverflow. Accumulating errors like you do is a design error. I don't do general .NET programming consulting.

**Comment by my151and** [comment]
Please focus on the issue on this post. I just  set errors manually to  fast reproduce the problem. It's not real project.

**Comment by ShannonZ** [comment]
@my151and You'd better use the default editor instead of MahApps.
It seems that these two libraries were not much compatible with each other, especially in the data validation mechanism.

**Comment by my151and** [comment]
@ShannonZ
I found that it's caused by the conflicts between MahApp.Metro and SF. It works as expected when using default editor. What's confusing is that when binding class property to a MahApp NumericUpDown (without SF), the same code also works fine.
So I agree with you that MahApp.Metro and SofltFluent.Windows are not compatible in data validation representation.

**Comment by my151and** [comment]
I made a similar class to generator Description (TextBlock) + Content Editor (Editable UI Control) according to some Data Annotation, and using FluentValidation to do data validation, UI Controls were from Mahapps. These works fine! Each library implements a single function.

@smourier No offense. I think Data Validation should be under control of who use SF, not SF itself.

**Comment by smourier** [comment]
You can override everything with this property grid, and it's open source, so it's not very difficult to override most behavior. As for Mahapps, it can cause quite a number of problems because it's a big thing that changes internal WPF behavior deeply in many aspects. The property grid is only tested with WPF, not with Mahapps.

**Comment by ShannonZ** [comment]
I agree with smourier. It works well if using native WPF.
