### ISSUE TITLE
Project Outdated?

### ISSUE THREAD

**Issue by Zearath** [SoftFluent/SoftFluent.Windows#20]
It's not working anymore, at least not for me and I did exactly what the "Wiki Getting Started" told me^^

**Comment by smourier** [comment]
What doesn't work. No even looking at the wiki, I've just cloned it, compiled it and it works w/o any issue.

**Comment by Zearath** [comment]
Thanks for the fast reply ! :)
It was my mistake, I thought the NuGet SoftFluent.Windows would already be in the cloned project.
So I added the required NuGet and changed the "Start Project" to "SoftFluent.Windows.Samples" and it works 👍 

Thanks for this project :)
