### ISSUE TITLE
Validate problem

### ISSUE THREAD

**Issue by PhilYang** [SoftFluent/SoftFluent.Windows#4]
I download and run samples project,
When to override a Validate method in Customer
**memberName** always null, why?

![default](https://cloud.githubusercontent.com/assets/11531055/16658696/e29353e8-4499-11e6-97bf-f76af90d0353.png)

**Comment by smourier** [comment]
Validate will be called with a non null member through IDataErrorInfo usage (IDataErrorInfo is implemented on AutoObject that you can have a look at it in the SoftFluent.Windows project). So it depends on your context. With WPF, you can use it with sample code like this one: http://stackoverflow.com/questions/14023552/how-to-use-idataerrorinfo-error-in-a-wpf-program You can also use it yourself if you need to.

**Comment by PhilYang** [comment]
Oh, I see. Thank you.
