### ISSUE TITLE
Is user-input validation available?

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#5]
`[DisplayName("PRG")]
  public int PRG { get; set; }`

If the input is illegal, the PropertyGridProperty throw an exception like this:
An exception of type 'System.ArgumentException' occurred in SoftFluent.Windows.dll but was not handled in user code

Additional information: Cannot convert value {4.} to type 'System.Int32'.

My question is: How to validate the input when using SoftFluent.Windows?

**Comment by smourier** [comment]
There is indeed an exception, but it's a first chance exception that is caught by WPF wich contains validation code. It's then used by the PropertyGrid template which contains this code (in PropertyGrid.xaml):

        ....
        <Style x:Key="ValidationTextBox" TargetType="{x:Type TextBox}">
            <Setter Property="Validation.ErrorTemplate">
                <Setter.Value>
                    <ControlTemplate>
                        <Border BorderThickness="1" BorderBrush="Red" Width="1" Height="23"></Border>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
            <Style.Triggers>
                <Trigger Property="Validation.HasError" Value="true">
                    <Setter Property="DataGridCell.ToolTip" Value="{Binding RelativeSource={RelativeSource Self}, Path=(Validation.Errors).CurrentItem.ErrorContent}" />
                </Trigger>
            </Style.Triggers>
        </Style>
        ....

This is all standard WPF (that you can see with the usage of Validation.XXX paths). This code causes the input to be surrounded by a red border, and a tooltip is added. Here is what it displays:

![propertygrid2](https://user-images.githubusercontent.com/5328574/28959526-14bc271e-78fb-11e7-9fa0-23df74a551e3.png)


So, by default, the input is automatically validated. If you want to validate it differently, then, you'll have to provide another style for the TextBox

**Comment by ShannonZ** [comment]
Thanks a lot. Elegent solution!

**Comment by ShannonZ** [comment]
@smourier 
I want to set the value to the old value when there is any exception. How to implement this?

**Comment by smourier** [comment]
How would do you that in terms of UI/UX?
