### ISSUE TITLE
How to refresh the content in UI when validation fails?

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#6]
[PropertyGridOptions(SortOrder = 14)]
public float RG { get; set; }=1; // positive integer

RG <----> txt.Text
When user typed -1 into  txt, an validation will return false. Then RG won't change to -1.
Is it possible to refresh the text("-1") to the correct value of RG when validation return false?

**Comment by smourier** [comment]
The only thing that's built-in is the user can do a CTRL-Z to revert to the original text. Other than that you would have to write a custom editor for this property/type of property. All that depends on how you want to do it in terms of UI/UX.

**Comment by ShannonZ** [comment]
So each property needs a customized editor？

**Comment by smourier** [comment]
It depends how you want to do the "refresh the text" action. Is it automatic? when? Is it manual? how? All properties are not the same, some can be very custom types that have no concept of "text", etc. The whole thing is open source so you can always change its default behavior.

If you only want it on some properties, the easiest is to declare a custom editor (usually in app.xaml) and add it to PropertyGridOptions like the WebSite property in model.cs :

        [PropertyGridOptions(EditorDataTemplateResourceKey = "CustomEditor")]
        public string WebSite
        {
            get { return GetProperty<string>(); }
            set { SetProperty(value); }
        }

**Comment by ShannonZ** [comment]
WOW... Thanks very much!
