### ISSUE TITLE
How to hidden the horizental&vertical scrollbar

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#7]
How to hidden the  ScrollBar?

**Comment by smourier** [comment]
which scrollbar?

**Comment by ShannonZ** [comment]
![1](https://user-images.githubusercontent.com/7865691/29261569-b703aad8-8102-11e7-8dda-0bd12082a0e5.png)

**Comment by smourier** [comment]
The PropertyGrid's heart is a standard WPF DataGrid which is accessible using the PropertyGrid's BaseGrid public property. So, if your PropertyGrid is named MyGrid, you can do this:

    // vertical bar, the inner DataGrid is surrounded by a ScrollViewer
    ((ScrollViewer)MyGrid.BaseGrid.Parent).VerticalScrollBarVisibility = ScrollBarVisibility.Auto;
    
    // horizontal bar
    MyGrid.BaseGrid.HorizontalScrollBarVisibility = ScrollBarVisibility.Hidden;

**Comment by ShannonZ** [comment]
I've done this by modifying PropertyGrid.xaml. Thank you very much.
