### ISSUE TITLE
How to set "IsExpanded" of each Expander?

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#8]
Is the property "IsExpanded" of each Expanders accessible? I want to expand some frequently used categories and collapse others.

**Comment by smourier** [comment]
Expanders are defined using the standard WPF patttern: https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-group-sort-and-filter-data-in-the-datagrid-control

Here are two utilities methods to get expanders from a DataGrid:

    public static IEnumerable<Expander> EnumerateExpanders(this DataGrid grid)
    {
        if (grid == null)
            throw new ArgumentNullException(nameof(grid));

        foreach (var item in grid.EnumerateVisualChildren(true, true).OfType<GroupItem>())
        {
            var expander = item.FindVisualChild<Expander>(ex => true);
            if (expander != null)
                yield return expander;
        }
    }

    public static Expander GetExpander(this DataGrid grid, object groupName)
    {
        if (grid == null)
            throw new ArgumentNullException(nameof(grid));

        if (groupName == null)
            throw new ArgumentNullException(nameof(groupName));

        foreach (var expander in EnumerateExpanders(grid))
        {
            var group = expander.DataContext as CollectionViewGroup;
            if (group != null && groupName.Equals(group.Name))
                return expander;
        }
        return null;
    }

They need EnumerateVisualChildren and FindVisualChild<T> methods defined in the Extensions.cs class in the PropertyGrid project (this could be made public).

Once you have that, you can do this with a "Dates and Times" category:

    MyGrid.BaseGrid.GetExpander("Dates and Times").IsExpanded = false;

Another solution I won't detail is to use databinding on the Expander and bind it on some custom object.

**Comment by ShannonZ** [comment]
After running 
              MyGrid.BaseGrid.GetExpander("Dates and Times").IsExpanded = false;

All the UI became blank.
(I have made EnumerateVisualChildren and FindVisualChild public)

**Comment by smourier** [comment]
It works fine on the provided sample.

**Comment by ShannonZ** [comment]
@smourier Can you give me the source code of this small sample?

**Comment by smourier** [comment]
I'm always talking about SoftFluent.Windows.Samples in the same repo. You'll just have to add the methods in my post
